# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tk-PerlMethodList
version:      0.01
version_from: lib/Tk/PerlMethodList.pm
installdirs:  site
requires:
    Class::ISA:                    0.33
    File::Slurp:                   9999.08
    Tk:                            8.4
    Tk::LabEntry:                  4.006

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
